# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'FabletonHelpers.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'FabletonHelpers.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'TestProject.csproj'
    arguments: '--no-build --logger "trx;LogFileName=tests-log.trx'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'nuget push FabletonHelpers.${{ BuildNumber }}.nupkg --api-key oy2obbpkkyg26sdds4zqbqwu4dm4jrterjpnyurbp42ozi --source https://api.nuget.org/v3/index.json'